version: '3.8'

services: 
  my-redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: "always"
                 
  rabbitmq:
    hostname: ${RABBIT_HOST}
    build:
      dockerfile: "rabbitmq-dockerfile"
    ports:
      - "15671:15671"
      - "15672:15672"
    restart: "always"
      
  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_PASSWORD}
    ports: 
      - "1433:1433"
    restart: "always"